language: java
jdk:
  - oraclejdk8
addons:
  sonarqube: true
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: releases
  api_key: $GIT_HUB_O_AUTH_TOKEN
  file: sm-combat.zip
  skip_cleanup: true
  on:
    tags: true
